version: "3"

services:
  extw-integ:
    image: extw-integ
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
    - "8080:8080"
    links:
      - redis
  redis:
    image: redis
    ports:
    - "6379:6379"
