---
kind: ConfigMap
apiVersion: v1
metadata:
  name: properties
  namespace: {{ .Values.namespace | default "elysium" }}
  labels:
  {{- include "extw-integ.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{- .Files.Get "application.properties" | nindent 4 }}
