apiVersion: v1
kind: Service
metadata:
  name: {{ include "extw-integ-v1.fullname" . }}
  namespace: {{ .Values.namespace | default "elysium" }}
  labels:
    {{- include "extw-integ-v1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: extw-integ
      protocol: TCP
      name: rgs
  selector:
    {{- include "extw-integ-v1.selectorLabels" . | nindent 4 }}
