name: DEV - Deploy external wallet integrations

on:
  workflow_dispatch:
  push:
    branches:
      - master
  paths-ignore:
    - 'charts/rgs-v2/Chart.yaml'
    - '**/.gitignore'
    - '.github/**'

jobs:
# skip test job until tests have been enabled in common.jar
  build:
    runs-on: ubuntu-latest
    env:
      # (check/change BUILDER_TOKEN so that it is unique for the extw-integ project) 
      BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN  }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
#   needs: test   
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        id: tag
        env:
          GITHUB_TOKEN: ${{ env.BUILDER_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - run: |
          echo building extw-integ ${{ steps.tag.outputs.new_tag }}
          docker login harbor.elysiumstudios.se -u ${{ env.HARBOR_USERNAME }} -p ${{ env.HARBOR_PASSWORD }}
          docker build -f src/main/docker/Dockerfile.jvm -t harbor.elysiumstudios.se/elysium/extw-integ:${{ steps.tag.outputs.new_tag }} .       
      - name: Update and push extw-integ helm chart
        run: |
          sed -i -e 's/appVersion:.*/appVersion: '${{ steps.tag.outputs.new_tag }}'/g' -e 's/^version:.*/version: '${{ steps.tag.outputs.new_tag }}'/' charts/extw-integ/Chart.yaml
          git config --global user.email "workflow@elysiumstudios.se"
          git config --global user.name "Workflow"
          git add charts/extw-integ/Chart.yaml 
          git commit -m "Deploy dev extw-integ ${{ steps.tag.outputs.new_tag }}"
          git push
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add --username=${{ env.HARBOR_USERNAME }} --password=${{ env.HARBOR_PASSWORD }} elysium-charts https://harbor.elysiumstudios.se/chartrepo/elysium/
          helm cm-push charts/extw-integ/ elysium-charts

      - uses: actions/checkout@v2
        with:
          repository: Elysium-Studios/infrastructure
          token: ${{ env.BUILDER_TOKEN }}
          path: infrastructure
          
      - name: Update extw-integ release in flux repo
        run: |
          cd infrastructure/
          sed -i -e 's/version:.*/version: "${{ steps.tag.outputs.new_tag }}"/g' dev/apps-infra/deployments/extw-integ-v1/release.yaml
          git config --global user.email "workflow@elysiumstudios.se"
          git config --global user.name "EXTW-INTEG-V1 Workflow"
          git add dev/apps-infra/deployments/extw-integ-v1/release.yaml
          git commit -m "Deploy extw-integ-v1 ${{ steps.tag.outputs.new_tag }}"
          git push
